import {
    MD3LightTheme as DefaultLightTheme,
    MD3DarkTheme as DefaultDarkTheme,
    MD3LightTheme as DefaultTheme,
} from "react-native-paper";

export const PaperTheme = {
    ...DefaultTheme,
    colors: {
        ...DefaultTheme.colors,
        primary: "#144985",
        secondary: "#1E88E5",
        background: "#ffffff",
        surface: "#ffffff",
        text: "#000000",
        error: "#f83737ff",
    },
};
export const PaperLightTheme = {
    ...DefaultLightTheme,
    colors: {
        ...DefaultLightTheme.colors,
        primary: "#144985",
        onPrimary: "#FFFFFF",
        primaryContainer: "#D9E8FA",
        onPrimaryContainer: "#0D3461",
        secondary: "#1E88E5",
        onSecondary: "#FFFFFF",
        background: "#ffffff",
        surface: "#FFFFFF",
        surfaceVariant: "#F1F5F9",
        onSurface: "#1F2937",
        onSurfaceVariant: "#64748B",
        outline: "#CBD5E1",
        error: "#DC2626",
        onError: "#FFFFFF",
        success: "#15803D",
        onSuccess: "#FFFFFF",
        warning: "#B45309",
        onWarning: "#FFFFFF",
        info: "#1976D2",
        text: "#333333",
    },
};
export const PaperDarkTheme = {
    ...DefaultDarkTheme,
    colors: {
        ...DefaultDarkTheme.colors,
        primary: "#90CAF9",
        onPrimary: "#082F49",
        primaryContainer: "#164E63",
        onPrimaryContainer: "#BAE6FD",
        secondary: "#64B5F6",
        onSecondary: "#082F49",
        background: "#121212",
        surface: "#182027",
        surfaceVariant: "#26333D",
        onSurface: "#F1F5F9",
        onSurfaceVariant: "#B7C3CF",
        outline: "#52616D",
        error: "#F87171",
        onError: "#450A0A",
        success: "#4ADE80",
        onSuccess: "#052E16",
        warning: "#FBBF24",
        onWarning: "#422006",
        info: "#60A5FA",
        text: "#ffffff",
    },
}
